[package]
name = "parsec-hello-decrypt"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parsec-client = "0.14.0"
base64 = "0.13.0"
